// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class AzureBlobMount extends pulumi.CustomResource {
    /**
     * Get an existing AzureBlobMount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AzureBlobMountState, opts?: pulumi.CustomResourceOptions): AzureBlobMount {
        return new AzureBlobMount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'databricks:azure/azureBlobMount:AzureBlobMount';

    /**
     * Returns true if the given object is an instance of AzureBlobMount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AzureBlobMount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AzureBlobMount.__pulumiType;
    }

    public readonly authType!: pulumi.Output<string>;
    public readonly clusterId!: pulumi.Output<string>;
    public readonly containerName!: pulumi.Output<string>;
    public readonly directory!: pulumi.Output<string>;
    public readonly mountName!: pulumi.Output<string>;
    public readonly storageAccountName!: pulumi.Output<string>;
    public readonly tokenSecretKey!: pulumi.Output<string>;
    public readonly tokenSecretScope!: pulumi.Output<string>;

    /**
     * Create a AzureBlobMount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AzureBlobMountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AzureBlobMountArgs | AzureBlobMountState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as AzureBlobMountState | undefined;
            inputs["authType"] = state ? state.authType : undefined;
            inputs["clusterId"] = state ? state.clusterId : undefined;
            inputs["containerName"] = state ? state.containerName : undefined;
            inputs["directory"] = state ? state.directory : undefined;
            inputs["mountName"] = state ? state.mountName : undefined;
            inputs["storageAccountName"] = state ? state.storageAccountName : undefined;
            inputs["tokenSecretKey"] = state ? state.tokenSecretKey : undefined;
            inputs["tokenSecretScope"] = state ? state.tokenSecretScope : undefined;
        } else {
            const args = argsOrState as AzureBlobMountArgs | undefined;
            if (!args || args.authType === undefined) {
                throw new Error("Missing required property 'authType'");
            }
            if (!args || args.clusterId === undefined) {
                throw new Error("Missing required property 'clusterId'");
            }
            if (!args || args.containerName === undefined) {
                throw new Error("Missing required property 'containerName'");
            }
            if (!args || args.mountName === undefined) {
                throw new Error("Missing required property 'mountName'");
            }
            if (!args || args.storageAccountName === undefined) {
                throw new Error("Missing required property 'storageAccountName'");
            }
            if (!args || args.tokenSecretKey === undefined) {
                throw new Error("Missing required property 'tokenSecretKey'");
            }
            if (!args || args.tokenSecretScope === undefined) {
                throw new Error("Missing required property 'tokenSecretScope'");
            }
            inputs["authType"] = args ? args.authType : undefined;
            inputs["clusterId"] = args ? args.clusterId : undefined;
            inputs["containerName"] = args ? args.containerName : undefined;
            inputs["directory"] = args ? args.directory : undefined;
            inputs["mountName"] = args ? args.mountName : undefined;
            inputs["storageAccountName"] = args ? args.storageAccountName : undefined;
            inputs["tokenSecretKey"] = args ? args.tokenSecretKey : undefined;
            inputs["tokenSecretScope"] = args ? args.tokenSecretScope : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(AzureBlobMount.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AzureBlobMount resources.
 */
export interface AzureBlobMountState {
    readonly authType?: pulumi.Input<string>;
    readonly clusterId?: pulumi.Input<string>;
    readonly containerName?: pulumi.Input<string>;
    readonly directory?: pulumi.Input<string>;
    readonly mountName?: pulumi.Input<string>;
    readonly storageAccountName?: pulumi.Input<string>;
    readonly tokenSecretKey?: pulumi.Input<string>;
    readonly tokenSecretScope?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AzureBlobMount resource.
 */
export interface AzureBlobMountArgs {
    readonly authType: pulumi.Input<string>;
    readonly clusterId: pulumi.Input<string>;
    readonly containerName: pulumi.Input<string>;
    readonly directory?: pulumi.Input<string>;
    readonly mountName: pulumi.Input<string>;
    readonly storageAccountName: pulumi.Input<string>;
    readonly tokenSecretKey: pulumi.Input<string>;
    readonly tokenSecretScope: pulumi.Input<string>;
}
