// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type AwsS3Mount struct {
	pulumi.CustomResourceState

	ClusterId    pulumi.StringOutput `pulumi:"clusterId"`
	MountName    pulumi.StringOutput `pulumi:"mountName"`
	S3BucketName pulumi.StringOutput `pulumi:"s3BucketName"`
}

// NewAwsS3Mount registers a new resource with the given unique name, arguments, and options.
func NewAwsS3Mount(ctx *pulumi.Context,
	name string, args *AwsS3MountArgs, opts ...pulumi.ResourceOption) (*AwsS3Mount, error) {
	if args == nil || args.ClusterId == nil {
		return nil, errors.New("missing required argument 'ClusterId'")
	}
	if args == nil || args.MountName == nil {
		return nil, errors.New("missing required argument 'MountName'")
	}
	if args == nil || args.S3BucketName == nil {
		return nil, errors.New("missing required argument 'S3BucketName'")
	}
	if args == nil {
		args = &AwsS3MountArgs{}
	}
	var resource AwsS3Mount
	err := ctx.RegisterResource("databricks:index/awsS3Mount:AwsS3Mount", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAwsS3Mount gets an existing AwsS3Mount resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAwsS3Mount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AwsS3MountState, opts ...pulumi.ResourceOption) (*AwsS3Mount, error) {
	var resource AwsS3Mount
	err := ctx.ReadResource("databricks:index/awsS3Mount:AwsS3Mount", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AwsS3Mount resources.
type awsS3MountState struct {
	ClusterId    *string `pulumi:"clusterId"`
	MountName    *string `pulumi:"mountName"`
	S3BucketName *string `pulumi:"s3BucketName"`
}

type AwsS3MountState struct {
	ClusterId    pulumi.StringPtrInput
	MountName    pulumi.StringPtrInput
	S3BucketName pulumi.StringPtrInput
}

func (AwsS3MountState) ElementType() reflect.Type {
	return reflect.TypeOf((*awsS3MountState)(nil)).Elem()
}

type awsS3MountArgs struct {
	ClusterId    string `pulumi:"clusterId"`
	MountName    string `pulumi:"mountName"`
	S3BucketName string `pulumi:"s3BucketName"`
}

// The set of arguments for constructing a AwsS3Mount resource.
type AwsS3MountArgs struct {
	ClusterId    pulumi.StringInput
	MountName    pulumi.StringInput
	S3BucketName pulumi.StringInput
}

func (AwsS3MountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*awsS3MountArgs)(nil)).Elem()
}
