// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func DatabricksNotebook(ctx *pulumi.Context, args *DatabricksNotebookArgs, opts ...pulumi.InvokeOption) (*DatabricksNotebookResult, error) {
	var rv DatabricksNotebookResult
	err := ctx.Invoke("databricks:index/databricksNotebook:DatabricksNotebook", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking DatabricksNotebook.
type DatabricksNotebookArgs struct {
	Format string `pulumi:"format"`
	Path   string `pulumi:"path"`
}

// A collection of values returned by DatabricksNotebook.
type DatabricksNotebookResult struct {
	Content string `pulumi:"content"`
	Format  string `pulumi:"format"`
	// The provider-assigned unique ID for this managed resource.
	Id         string `pulumi:"id"`
	Language   string `pulumi:"language"`
	ObjectId   int    `pulumi:"objectId"`
	ObjectType string `pulumi:"objectType"`
	Path       string `pulumi:"path"`
}
