// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetDefaultUserRoles(ctx *pulumi.Context, args *GetDefaultUserRolesArgs, opts ...pulumi.InvokeOption) (*GetDefaultUserRolesResult, error) {
	var rv GetDefaultUserRolesResult
	err := ctx.Invoke("databricks:index/getDefaultUserRoles:getDefaultUserRoles", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDefaultUserRoles.
type GetDefaultUserRolesArgs struct {
	DefaultUsername string `pulumi:"defaultUsername"`
}

// A collection of values returned by getDefaultUserRoles.
type GetDefaultUserRolesResult struct {
	DefaultUsername string `pulumi:"defaultUsername"`
	// The provider-assigned unique ID for this managed resource.
	Id    string   `pulumi:"id"`
	Roles []string `pulumi:"roles"`
}
