// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetDbfsFilePaths(ctx *pulumi.Context, args *GetDbfsFilePathsArgs, opts ...pulumi.InvokeOption) (*GetDbfsFilePathsResult, error) {
	var rv GetDbfsFilePathsResult
	err := ctx.Invoke("databricks:index/getDbfsFilePaths:getDbfsFilePaths", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDbfsFilePaths.
type GetDbfsFilePathsArgs struct {
	Path      string `pulumi:"path"`
	Recursive bool   `pulumi:"recursive"`
}

// A collection of values returned by getDbfsFilePaths.
type GetDbfsFilePathsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id        string                     `pulumi:"id"`
	Path      string                     `pulumi:"path"`
	PathLists []GetDbfsFilePathsPathList `pulumi:"pathLists"`
	Recursive bool                       `pulumi:"recursive"`
}
