// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupDbfsFile(ctx *pulumi.Context, args *LookupDbfsFileArgs, opts ...pulumi.InvokeOption) (*LookupDbfsFileResult, error) {
	var rv LookupDbfsFileResult
	err := ctx.Invoke("databricks:index/getDbfsFile:getDbfsFile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDbfsFile.
type LookupDbfsFileArgs struct {
	LimitFileSize bool   `pulumi:"limitFileSize"`
	Path          string `pulumi:"path"`
}

// A collection of values returned by getDbfsFile.
type LookupDbfsFileResult struct {
	Content  string `pulumi:"content"`
	FileSize int    `pulumi:"fileSize"`
	// The provider-assigned unique ID for this managed resource.
	Id            string `pulumi:"id"`
	LimitFileSize bool   `pulumi:"limitFileSize"`
	Path          string `pulumi:"path"`
}
