// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetNotebookPaths(ctx *pulumi.Context, args *GetNotebookPathsArgs, opts ...pulumi.InvokeOption) (*GetNotebookPathsResult, error) {
	var rv GetNotebookPathsResult
	err := ctx.Invoke("databricks:index/getNotebookPaths:getNotebookPaths", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNotebookPaths.
type GetNotebookPathsArgs struct {
	Path      string `pulumi:"path"`
	Recursive bool   `pulumi:"recursive"`
}

// A collection of values returned by getNotebookPaths.
type GetNotebookPathsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                string                             `pulumi:"id"`
	NotebookPathLists []GetNotebookPathsNotebookPathList `pulumi:"notebookPathLists"`
	Path              string                             `pulumi:"path"`
	Recursive         bool                               `pulumi:"recursive"`
}
