// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type GroupInstanceProfile struct {
	pulumi.CustomResourceState

	GroupId           pulumi.StringOutput `pulumi:"groupId"`
	InstanceProfileId pulumi.StringOutput `pulumi:"instanceProfileId"`
}

// NewGroupInstanceProfile registers a new resource with the given unique name, arguments, and options.
func NewGroupInstanceProfile(ctx *pulumi.Context,
	name string, args *GroupInstanceProfileArgs, opts ...pulumi.ResourceOption) (*GroupInstanceProfile, error) {
	if args == nil || args.GroupId == nil {
		return nil, errors.New("missing required argument 'GroupId'")
	}
	if args == nil || args.InstanceProfileId == nil {
		return nil, errors.New("missing required argument 'InstanceProfileId'")
	}
	if args == nil {
		args = &GroupInstanceProfileArgs{}
	}
	var resource GroupInstanceProfile
	err := ctx.RegisterResource("databricks:index/groupInstanceProfile:GroupInstanceProfile", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGroupInstanceProfile gets an existing GroupInstanceProfile resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGroupInstanceProfile(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GroupInstanceProfileState, opts ...pulumi.ResourceOption) (*GroupInstanceProfile, error) {
	var resource GroupInstanceProfile
	err := ctx.ReadResource("databricks:index/groupInstanceProfile:GroupInstanceProfile", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GroupInstanceProfile resources.
type groupInstanceProfileState struct {
	GroupId           *string `pulumi:"groupId"`
	InstanceProfileId *string `pulumi:"instanceProfileId"`
}

type GroupInstanceProfileState struct {
	GroupId           pulumi.StringPtrInput
	InstanceProfileId pulumi.StringPtrInput
}

func (GroupInstanceProfileState) ElementType() reflect.Type {
	return reflect.TypeOf((*groupInstanceProfileState)(nil)).Elem()
}

type groupInstanceProfileArgs struct {
	GroupId           string `pulumi:"groupId"`
	InstanceProfileId string `pulumi:"instanceProfileId"`
}

// The set of arguments for constructing a GroupInstanceProfile resource.
type GroupInstanceProfileArgs struct {
	GroupId           pulumi.StringInput
	InstanceProfileId pulumi.StringInput
}

func (GroupInstanceProfileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*groupInstanceProfileArgs)(nil)).Elem()
}
