// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type Group struct {
	pulumi.CustomResourceState

	AllowClusterCreate      pulumi.BoolPtrOutput `pulumi:"allowClusterCreate"`
	AllowInstancePoolCreate pulumi.BoolPtrOutput `pulumi:"allowInstancePoolCreate"`
	DisplayName             pulumi.StringOutput  `pulumi:"displayName"`
}

// NewGroup registers a new resource with the given unique name, arguments, and options.
func NewGroup(ctx *pulumi.Context,
	name string, args *GroupArgs, opts ...pulumi.ResourceOption) (*Group, error) {
	if args == nil || args.DisplayName == nil {
		return nil, errors.New("missing required argument 'DisplayName'")
	}
	if args == nil {
		args = &GroupArgs{}
	}
	var resource Group
	err := ctx.RegisterResource("databricks:index/group:Group", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGroup gets an existing Group resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GroupState, opts ...pulumi.ResourceOption) (*Group, error) {
	var resource Group
	err := ctx.ReadResource("databricks:index/group:Group", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Group resources.
type groupState struct {
	AllowClusterCreate      *bool   `pulumi:"allowClusterCreate"`
	AllowInstancePoolCreate *bool   `pulumi:"allowInstancePoolCreate"`
	DisplayName             *string `pulumi:"displayName"`
}

type GroupState struct {
	AllowClusterCreate      pulumi.BoolPtrInput
	AllowInstancePoolCreate pulumi.BoolPtrInput
	DisplayName             pulumi.StringPtrInput
}

func (GroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*groupState)(nil)).Elem()
}

type groupArgs struct {
	AllowClusterCreate      *bool  `pulumi:"allowClusterCreate"`
	AllowInstancePoolCreate *bool  `pulumi:"allowInstancePoolCreate"`
	DisplayName             string `pulumi:"displayName"`
}

// The set of arguments for constructing a Group resource.
type GroupArgs struct {
	AllowClusterCreate      pulumi.BoolPtrInput
	AllowInstancePoolCreate pulumi.BoolPtrInput
	DisplayName             pulumi.StringInput
}

func (GroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*groupArgs)(nil)).Elem()
}
