// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type InstancePool struct {
	pulumi.CustomResourceState

	AwsAttributes                      InstancePoolAwsAttributesPtrOutput `pulumi:"awsAttributes"`
	CustomTags                         pulumi.MapOutput                   `pulumi:"customTags"`
	DefaultTags                        pulumi.MapOutput                   `pulumi:"defaultTags"`
	DiskSpec                           InstancePoolDiskSpecPtrOutput      `pulumi:"diskSpec"`
	EnableElasticDisk                  pulumi.BoolPtrOutput               `pulumi:"enableElasticDisk"`
	IdleInstanceAutoterminationMinutes pulumi.IntOutput                   `pulumi:"idleInstanceAutoterminationMinutes"`
	InstancePoolName                   pulumi.StringOutput                `pulumi:"instancePoolName"`
	MaxCapacity                        pulumi.IntOutput                   `pulumi:"maxCapacity"`
	MinIdleInstances                   pulumi.IntOutput                   `pulumi:"minIdleInstances"`
	NodeTypeId                         pulumi.StringOutput                `pulumi:"nodeTypeId"`
	PreloadedSparkVersions             pulumi.StringArrayOutput           `pulumi:"preloadedSparkVersions"`
	State                              pulumi.StringOutput                `pulumi:"state"`
}

// NewInstancePool registers a new resource with the given unique name, arguments, and options.
func NewInstancePool(ctx *pulumi.Context,
	name string, args *InstancePoolArgs, opts ...pulumi.ResourceOption) (*InstancePool, error) {
	if args == nil || args.IdleInstanceAutoterminationMinutes == nil {
		return nil, errors.New("missing required argument 'IdleInstanceAutoterminationMinutes'")
	}
	if args == nil || args.InstancePoolName == nil {
		return nil, errors.New("missing required argument 'InstancePoolName'")
	}
	if args == nil || args.MaxCapacity == nil {
		return nil, errors.New("missing required argument 'MaxCapacity'")
	}
	if args == nil || args.MinIdleInstances == nil {
		return nil, errors.New("missing required argument 'MinIdleInstances'")
	}
	if args == nil || args.NodeTypeId == nil {
		return nil, errors.New("missing required argument 'NodeTypeId'")
	}
	if args == nil {
		args = &InstancePoolArgs{}
	}
	var resource InstancePool
	err := ctx.RegisterResource("databricks:index/instancePool:InstancePool", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstancePool gets an existing InstancePool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstancePool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstancePoolState, opts ...pulumi.ResourceOption) (*InstancePool, error) {
	var resource InstancePool
	err := ctx.ReadResource("databricks:index/instancePool:InstancePool", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InstancePool resources.
type instancePoolState struct {
	AwsAttributes                      *InstancePoolAwsAttributes `pulumi:"awsAttributes"`
	CustomTags                         map[string]interface{}     `pulumi:"customTags"`
	DefaultTags                        map[string]interface{}     `pulumi:"defaultTags"`
	DiskSpec                           *InstancePoolDiskSpec      `pulumi:"diskSpec"`
	EnableElasticDisk                  *bool                      `pulumi:"enableElasticDisk"`
	IdleInstanceAutoterminationMinutes *int                       `pulumi:"idleInstanceAutoterminationMinutes"`
	InstancePoolName                   *string                    `pulumi:"instancePoolName"`
	MaxCapacity                        *int                       `pulumi:"maxCapacity"`
	MinIdleInstances                   *int                       `pulumi:"minIdleInstances"`
	NodeTypeId                         *string                    `pulumi:"nodeTypeId"`
	PreloadedSparkVersions             []string                   `pulumi:"preloadedSparkVersions"`
	State                              *string                    `pulumi:"state"`
}

type InstancePoolState struct {
	AwsAttributes                      InstancePoolAwsAttributesPtrInput
	CustomTags                         pulumi.MapInput
	DefaultTags                        pulumi.MapInput
	DiskSpec                           InstancePoolDiskSpecPtrInput
	EnableElasticDisk                  pulumi.BoolPtrInput
	IdleInstanceAutoterminationMinutes pulumi.IntPtrInput
	InstancePoolName                   pulumi.StringPtrInput
	MaxCapacity                        pulumi.IntPtrInput
	MinIdleInstances                   pulumi.IntPtrInput
	NodeTypeId                         pulumi.StringPtrInput
	PreloadedSparkVersions             pulumi.StringArrayInput
	State                              pulumi.StringPtrInput
}

func (InstancePoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*instancePoolState)(nil)).Elem()
}

type instancePoolArgs struct {
	AwsAttributes                      *InstancePoolAwsAttributes `pulumi:"awsAttributes"`
	CustomTags                         map[string]interface{}     `pulumi:"customTags"`
	DiskSpec                           *InstancePoolDiskSpec      `pulumi:"diskSpec"`
	EnableElasticDisk                  *bool                      `pulumi:"enableElasticDisk"`
	IdleInstanceAutoterminationMinutes int                        `pulumi:"idleInstanceAutoterminationMinutes"`
	InstancePoolName                   string                     `pulumi:"instancePoolName"`
	MaxCapacity                        int                        `pulumi:"maxCapacity"`
	MinIdleInstances                   int                        `pulumi:"minIdleInstances"`
	NodeTypeId                         string                     `pulumi:"nodeTypeId"`
	PreloadedSparkVersions             []string                   `pulumi:"preloadedSparkVersions"`
	State                              *string                    `pulumi:"state"`
}

// The set of arguments for constructing a InstancePool resource.
type InstancePoolArgs struct {
	AwsAttributes                      InstancePoolAwsAttributesPtrInput
	CustomTags                         pulumi.MapInput
	DiskSpec                           InstancePoolDiskSpecPtrInput
	EnableElasticDisk                  pulumi.BoolPtrInput
	IdleInstanceAutoterminationMinutes pulumi.IntInput
	InstancePoolName                   pulumi.StringInput
	MaxCapacity                        pulumi.IntInput
	MinIdleInstances                   pulumi.IntInput
	NodeTypeId                         pulumi.StringInput
	PreloadedSparkVersions             pulumi.StringArrayInput
	State                              pulumi.StringPtrInput
}

func (InstancePoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instancePoolArgs)(nil)).Elem()
}
