// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type MwsWorkspaces struct {
	pulumi.CustomResourceState

	AccountId               pulumi.StringOutput                         `pulumi:"accountId"`
	AwsRegion               pulumi.StringOutput                         `pulumi:"awsRegion"`
	CreationTime            pulumi.IntOutput                            `pulumi:"creationTime"`
	CredentialsId           pulumi.StringOutput                         `pulumi:"credentialsId"`
	CustomerManagedKeyId    pulumi.StringPtrOutput                      `pulumi:"customerManagedKeyId"`
	DeploymentName          pulumi.StringOutput                         `pulumi:"deploymentName"`
	IsNoPublicIpEnabled     pulumi.BoolPtrOutput                        `pulumi:"isNoPublicIpEnabled"`
	NetworkErrorMessages    MwsWorkspacesNetworkErrorMessageArrayOutput `pulumi:"networkErrorMessages"`
	NetworkId               pulumi.StringPtrOutput                      `pulumi:"networkId"`
	StorageConfigurationId  pulumi.StringOutput                         `pulumi:"storageConfigurationId"`
	VerifyWorkspaceRunnning pulumi.BoolOutput                           `pulumi:"verifyWorkspaceRunnning"`
	WorkspaceId             pulumi.IntOutput                            `pulumi:"workspaceId"`
	WorkspaceName           pulumi.StringOutput                         `pulumi:"workspaceName"`
	WorkspaceStatus         pulumi.StringOutput                         `pulumi:"workspaceStatus"`
	WorkspaceStatusMessage  pulumi.StringOutput                         `pulumi:"workspaceStatusMessage"`
	WorkspaceUrl            pulumi.StringOutput                         `pulumi:"workspaceUrl"`
}

// NewMwsWorkspaces registers a new resource with the given unique name, arguments, and options.
func NewMwsWorkspaces(ctx *pulumi.Context,
	name string, args *MwsWorkspacesArgs, opts ...pulumi.ResourceOption) (*MwsWorkspaces, error) {
	if args == nil || args.AccountId == nil {
		return nil, errors.New("missing required argument 'AccountId'")
	}
	if args == nil || args.AwsRegion == nil {
		return nil, errors.New("missing required argument 'AwsRegion'")
	}
	if args == nil || args.CredentialsId == nil {
		return nil, errors.New("missing required argument 'CredentialsId'")
	}
	if args == nil || args.DeploymentName == nil {
		return nil, errors.New("missing required argument 'DeploymentName'")
	}
	if args == nil || args.StorageConfigurationId == nil {
		return nil, errors.New("missing required argument 'StorageConfigurationId'")
	}
	if args == nil || args.VerifyWorkspaceRunnning == nil {
		return nil, errors.New("missing required argument 'VerifyWorkspaceRunnning'")
	}
	if args == nil || args.WorkspaceName == nil {
		return nil, errors.New("missing required argument 'WorkspaceName'")
	}
	if args == nil {
		args = &MwsWorkspacesArgs{}
	}
	var resource MwsWorkspaces
	err := ctx.RegisterResource("databricks:index/mwsWorkspaces:MwsWorkspaces", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMwsWorkspaces gets an existing MwsWorkspaces resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMwsWorkspaces(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MwsWorkspacesState, opts ...pulumi.ResourceOption) (*MwsWorkspaces, error) {
	var resource MwsWorkspaces
	err := ctx.ReadResource("databricks:index/mwsWorkspaces:MwsWorkspaces", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MwsWorkspaces resources.
type mwsWorkspacesState struct {
	AccountId               *string                            `pulumi:"accountId"`
	AwsRegion               *string                            `pulumi:"awsRegion"`
	CreationTime            *int                               `pulumi:"creationTime"`
	CredentialsId           *string                            `pulumi:"credentialsId"`
	CustomerManagedKeyId    *string                            `pulumi:"customerManagedKeyId"`
	DeploymentName          *string                            `pulumi:"deploymentName"`
	IsNoPublicIpEnabled     *bool                              `pulumi:"isNoPublicIpEnabled"`
	NetworkErrorMessages    []MwsWorkspacesNetworkErrorMessage `pulumi:"networkErrorMessages"`
	NetworkId               *string                            `pulumi:"networkId"`
	StorageConfigurationId  *string                            `pulumi:"storageConfigurationId"`
	VerifyWorkspaceRunnning *bool                              `pulumi:"verifyWorkspaceRunnning"`
	WorkspaceId             *int                               `pulumi:"workspaceId"`
	WorkspaceName           *string                            `pulumi:"workspaceName"`
	WorkspaceStatus         *string                            `pulumi:"workspaceStatus"`
	WorkspaceStatusMessage  *string                            `pulumi:"workspaceStatusMessage"`
	WorkspaceUrl            *string                            `pulumi:"workspaceUrl"`
}

type MwsWorkspacesState struct {
	AccountId               pulumi.StringPtrInput
	AwsRegion               pulumi.StringPtrInput
	CreationTime            pulumi.IntPtrInput
	CredentialsId           pulumi.StringPtrInput
	CustomerManagedKeyId    pulumi.StringPtrInput
	DeploymentName          pulumi.StringPtrInput
	IsNoPublicIpEnabled     pulumi.BoolPtrInput
	NetworkErrorMessages    MwsWorkspacesNetworkErrorMessageArrayInput
	NetworkId               pulumi.StringPtrInput
	StorageConfigurationId  pulumi.StringPtrInput
	VerifyWorkspaceRunnning pulumi.BoolPtrInput
	WorkspaceId             pulumi.IntPtrInput
	WorkspaceName           pulumi.StringPtrInput
	WorkspaceStatus         pulumi.StringPtrInput
	WorkspaceStatusMessage  pulumi.StringPtrInput
	WorkspaceUrl            pulumi.StringPtrInput
}

func (MwsWorkspacesState) ElementType() reflect.Type {
	return reflect.TypeOf((*mwsWorkspacesState)(nil)).Elem()
}

type mwsWorkspacesArgs struct {
	AccountId               string  `pulumi:"accountId"`
	AwsRegion               string  `pulumi:"awsRegion"`
	CredentialsId           string  `pulumi:"credentialsId"`
	CustomerManagedKeyId    *string `pulumi:"customerManagedKeyId"`
	DeploymentName          string  `pulumi:"deploymentName"`
	IsNoPublicIpEnabled     *bool   `pulumi:"isNoPublicIpEnabled"`
	NetworkId               *string `pulumi:"networkId"`
	StorageConfigurationId  string  `pulumi:"storageConfigurationId"`
	VerifyWorkspaceRunnning bool    `pulumi:"verifyWorkspaceRunnning"`
	WorkspaceName           string  `pulumi:"workspaceName"`
}

// The set of arguments for constructing a MwsWorkspaces resource.
type MwsWorkspacesArgs struct {
	AccountId               pulumi.StringInput
	AwsRegion               pulumi.StringInput
	CredentialsId           pulumi.StringInput
	CustomerManagedKeyId    pulumi.StringPtrInput
	DeploymentName          pulumi.StringInput
	IsNoPublicIpEnabled     pulumi.BoolPtrInput
	NetworkId               pulumi.StringPtrInput
	StorageConfigurationId  pulumi.StringInput
	VerifyWorkspaceRunnning pulumi.BoolInput
	WorkspaceName           pulumi.StringInput
}

func (MwsWorkspacesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mwsWorkspacesArgs)(nil)).Elem()
}
