// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// The provider type for the databricks package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:databricks", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	AzureAuth *ProviderAzureAuth `pulumi:"azureAuth"`
	BasicAuth *ProviderBasicAuth `pulumi:"basicAuth"`
	// Location of the Databricks CLI credentials file, that is created by `databricks configure --token` command. By default,
	// it is located in ~/.databrickscfg. Check https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication for
	// docs. Config file credetials will only be used when host/token are not provided.
	ConfigFile *string `pulumi:"configFile"`
	Host       *string `pulumi:"host"`
	// Connection profile specified within ~/.databrickscfg. Please check
	// https://docs.databricks.com/dev-tools/cli/index.html#connection-profiles for documentation.
	Profile *string `pulumi:"profile"`
	Token   *string `pulumi:"token"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	AzureAuth ProviderAzureAuthPtrInput
	BasicAuth ProviderBasicAuthPtrInput
	// Location of the Databricks CLI credentials file, that is created by `databricks configure --token` command. By default,
	// it is located in ~/.databrickscfg. Check https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication for
	// docs. Config file credetials will only be used when host/token are not provided.
	ConfigFile pulumi.StringPtrInput
	Host       pulumi.StringPtrInput
	// Connection profile specified within ~/.databrickscfg. Please check
	// https://docs.databricks.com/dev-tools/cli/index.html#connection-profiles for documentation.
	Profile pulumi.StringPtrInput
	Token   pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}
