// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type ProviderAzureAuth struct {
	AzureRegion          string `pulumi:"azureRegion"`
	ClientId             string `pulumi:"clientId"`
	ClientSecret         string `pulumi:"clientSecret"`
	ManagedResourceGroup string `pulumi:"managedResourceGroup"`
	ResourceGroup        string `pulumi:"resourceGroup"`
	SubscriptionId       string `pulumi:"subscriptionId"`
	TenantId             string `pulumi:"tenantId"`
	WorkspaceName        string `pulumi:"workspaceName"`
}

// ProviderAzureAuthInput is an input type that accepts ProviderAzureAuthArgs and ProviderAzureAuthOutput values.
// You can construct a concrete instance of `ProviderAzureAuthInput` via:
//
// 		 ProviderAzureAuthArgs{...}
//
type ProviderAzureAuthInput interface {
	pulumi.Input

	ToProviderAzureAuthOutput() ProviderAzureAuthOutput
	ToProviderAzureAuthOutputWithContext(context.Context) ProviderAzureAuthOutput
}

type ProviderAzureAuthArgs struct {
	AzureRegion          pulumi.StringInput `pulumi:"azureRegion"`
	ClientId             pulumi.StringInput `pulumi:"clientId"`
	ClientSecret         pulumi.StringInput `pulumi:"clientSecret"`
	ManagedResourceGroup pulumi.StringInput `pulumi:"managedResourceGroup"`
	ResourceGroup        pulumi.StringInput `pulumi:"resourceGroup"`
	SubscriptionId       pulumi.StringInput `pulumi:"subscriptionId"`
	TenantId             pulumi.StringInput `pulumi:"tenantId"`
	WorkspaceName        pulumi.StringInput `pulumi:"workspaceName"`
}

func (ProviderAzureAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderAzureAuth)(nil)).Elem()
}

func (i ProviderAzureAuthArgs) ToProviderAzureAuthOutput() ProviderAzureAuthOutput {
	return i.ToProviderAzureAuthOutputWithContext(context.Background())
}

func (i ProviderAzureAuthArgs) ToProviderAzureAuthOutputWithContext(ctx context.Context) ProviderAzureAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderAzureAuthOutput)
}

func (i ProviderAzureAuthArgs) ToProviderAzureAuthPtrOutput() ProviderAzureAuthPtrOutput {
	return i.ToProviderAzureAuthPtrOutputWithContext(context.Background())
}

func (i ProviderAzureAuthArgs) ToProviderAzureAuthPtrOutputWithContext(ctx context.Context) ProviderAzureAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderAzureAuthOutput).ToProviderAzureAuthPtrOutputWithContext(ctx)
}

// ProviderAzureAuthPtrInput is an input type that accepts ProviderAzureAuthArgs, ProviderAzureAuthPtr and ProviderAzureAuthPtrOutput values.
// You can construct a concrete instance of `ProviderAzureAuthPtrInput` via:
//
// 		 ProviderAzureAuthArgs{...}
//
//  or:
//
// 		 nil
//
type ProviderAzureAuthPtrInput interface {
	pulumi.Input

	ToProviderAzureAuthPtrOutput() ProviderAzureAuthPtrOutput
	ToProviderAzureAuthPtrOutputWithContext(context.Context) ProviderAzureAuthPtrOutput
}

type providerAzureAuthPtrType ProviderAzureAuthArgs

func ProviderAzureAuthPtr(v *ProviderAzureAuthArgs) ProviderAzureAuthPtrInput {
	return (*providerAzureAuthPtrType)(v)
}

func (*providerAzureAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderAzureAuth)(nil)).Elem()
}

func (i *providerAzureAuthPtrType) ToProviderAzureAuthPtrOutput() ProviderAzureAuthPtrOutput {
	return i.ToProviderAzureAuthPtrOutputWithContext(context.Background())
}

func (i *providerAzureAuthPtrType) ToProviderAzureAuthPtrOutputWithContext(ctx context.Context) ProviderAzureAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderAzureAuthPtrOutput)
}

type ProviderAzureAuthOutput struct{ *pulumi.OutputState }

func (ProviderAzureAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderAzureAuth)(nil)).Elem()
}

func (o ProviderAzureAuthOutput) ToProviderAzureAuthOutput() ProviderAzureAuthOutput {
	return o
}

func (o ProviderAzureAuthOutput) ToProviderAzureAuthOutputWithContext(ctx context.Context) ProviderAzureAuthOutput {
	return o
}

func (o ProviderAzureAuthOutput) ToProviderAzureAuthPtrOutput() ProviderAzureAuthPtrOutput {
	return o.ToProviderAzureAuthPtrOutputWithContext(context.Background())
}

func (o ProviderAzureAuthOutput) ToProviderAzureAuthPtrOutputWithContext(ctx context.Context) ProviderAzureAuthPtrOutput {
	return o.ApplyT(func(v ProviderAzureAuth) *ProviderAzureAuth {
		return &v
	}).(ProviderAzureAuthPtrOutput)
}
func (o ProviderAzureAuthOutput) AzureRegion() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.AzureRegion }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.ClientId }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.ClientSecret }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) ManagedResourceGroup() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.ManagedResourceGroup }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) ResourceGroup() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.ResourceGroup }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) SubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.SubscriptionId }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.TenantId }).(pulumi.StringOutput)
}

func (o ProviderAzureAuthOutput) WorkspaceName() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderAzureAuth) string { return v.WorkspaceName }).(pulumi.StringOutput)
}

type ProviderAzureAuthPtrOutput struct{ *pulumi.OutputState }

func (ProviderAzureAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderAzureAuth)(nil)).Elem()
}

func (o ProviderAzureAuthPtrOutput) ToProviderAzureAuthPtrOutput() ProviderAzureAuthPtrOutput {
	return o
}

func (o ProviderAzureAuthPtrOutput) ToProviderAzureAuthPtrOutputWithContext(ctx context.Context) ProviderAzureAuthPtrOutput {
	return o
}

func (o ProviderAzureAuthPtrOutput) Elem() ProviderAzureAuthOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) ProviderAzureAuth { return *v }).(ProviderAzureAuthOutput)
}

func (o ProviderAzureAuthPtrOutput) AzureRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.AzureRegion
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) ClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.ClientId
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) ClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.ClientSecret
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) ManagedResourceGroup() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.ManagedResourceGroup
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) ResourceGroup() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.ResourceGroup
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) SubscriptionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.SubscriptionId
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) TenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.TenantId
	}).(pulumi.StringPtrOutput)
}

func (o ProviderAzureAuthPtrOutput) WorkspaceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAzureAuth) *string {
		if v == nil {
			return nil
		}
		return &v.WorkspaceName
	}).(pulumi.StringPtrOutput)
}

type ProviderBasicAuth struct {
	Password string `pulumi:"password"`
	Username string `pulumi:"username"`
}

// ProviderBasicAuthInput is an input type that accepts ProviderBasicAuthArgs and ProviderBasicAuthOutput values.
// You can construct a concrete instance of `ProviderBasicAuthInput` via:
//
// 		 ProviderBasicAuthArgs{...}
//
type ProviderBasicAuthInput interface {
	pulumi.Input

	ToProviderBasicAuthOutput() ProviderBasicAuthOutput
	ToProviderBasicAuthOutputWithContext(context.Context) ProviderBasicAuthOutput
}

type ProviderBasicAuthArgs struct {
	Password pulumi.StringInput `pulumi:"password"`
	Username pulumi.StringInput `pulumi:"username"`
}

func (ProviderBasicAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderBasicAuth)(nil)).Elem()
}

func (i ProviderBasicAuthArgs) ToProviderBasicAuthOutput() ProviderBasicAuthOutput {
	return i.ToProviderBasicAuthOutputWithContext(context.Background())
}

func (i ProviderBasicAuthArgs) ToProviderBasicAuthOutputWithContext(ctx context.Context) ProviderBasicAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderBasicAuthOutput)
}

func (i ProviderBasicAuthArgs) ToProviderBasicAuthPtrOutput() ProviderBasicAuthPtrOutput {
	return i.ToProviderBasicAuthPtrOutputWithContext(context.Background())
}

func (i ProviderBasicAuthArgs) ToProviderBasicAuthPtrOutputWithContext(ctx context.Context) ProviderBasicAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderBasicAuthOutput).ToProviderBasicAuthPtrOutputWithContext(ctx)
}

// ProviderBasicAuthPtrInput is an input type that accepts ProviderBasicAuthArgs, ProviderBasicAuthPtr and ProviderBasicAuthPtrOutput values.
// You can construct a concrete instance of `ProviderBasicAuthPtrInput` via:
//
// 		 ProviderBasicAuthArgs{...}
//
//  or:
//
// 		 nil
//
type ProviderBasicAuthPtrInput interface {
	pulumi.Input

	ToProviderBasicAuthPtrOutput() ProviderBasicAuthPtrOutput
	ToProviderBasicAuthPtrOutputWithContext(context.Context) ProviderBasicAuthPtrOutput
}

type providerBasicAuthPtrType ProviderBasicAuthArgs

func ProviderBasicAuthPtr(v *ProviderBasicAuthArgs) ProviderBasicAuthPtrInput {
	return (*providerBasicAuthPtrType)(v)
}

func (*providerBasicAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderBasicAuth)(nil)).Elem()
}

func (i *providerBasicAuthPtrType) ToProviderBasicAuthPtrOutput() ProviderBasicAuthPtrOutput {
	return i.ToProviderBasicAuthPtrOutputWithContext(context.Background())
}

func (i *providerBasicAuthPtrType) ToProviderBasicAuthPtrOutputWithContext(ctx context.Context) ProviderBasicAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderBasicAuthPtrOutput)
}

type ProviderBasicAuthOutput struct{ *pulumi.OutputState }

func (ProviderBasicAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderBasicAuth)(nil)).Elem()
}

func (o ProviderBasicAuthOutput) ToProviderBasicAuthOutput() ProviderBasicAuthOutput {
	return o
}

func (o ProviderBasicAuthOutput) ToProviderBasicAuthOutputWithContext(ctx context.Context) ProviderBasicAuthOutput {
	return o
}

func (o ProviderBasicAuthOutput) ToProviderBasicAuthPtrOutput() ProviderBasicAuthPtrOutput {
	return o.ToProviderBasicAuthPtrOutputWithContext(context.Background())
}

func (o ProviderBasicAuthOutput) ToProviderBasicAuthPtrOutputWithContext(ctx context.Context) ProviderBasicAuthPtrOutput {
	return o.ApplyT(func(v ProviderBasicAuth) *ProviderBasicAuth {
		return &v
	}).(ProviderBasicAuthPtrOutput)
}
func (o ProviderBasicAuthOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderBasicAuth) string { return v.Password }).(pulumi.StringOutput)
}

func (o ProviderBasicAuthOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderBasicAuth) string { return v.Username }).(pulumi.StringOutput)
}

type ProviderBasicAuthPtrOutput struct{ *pulumi.OutputState }

func (ProviderBasicAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderBasicAuth)(nil)).Elem()
}

func (o ProviderBasicAuthPtrOutput) ToProviderBasicAuthPtrOutput() ProviderBasicAuthPtrOutput {
	return o
}

func (o ProviderBasicAuthPtrOutput) ToProviderBasicAuthPtrOutputWithContext(ctx context.Context) ProviderBasicAuthPtrOutput {
	return o
}

func (o ProviderBasicAuthPtrOutput) Elem() ProviderBasicAuthOutput {
	return o.ApplyT(func(v *ProviderBasicAuth) ProviderBasicAuth { return *v }).(ProviderBasicAuthOutput)
}

func (o ProviderBasicAuthPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderBasicAuth) *string {
		if v == nil {
			return nil
		}
		return &v.Password
	}).(pulumi.StringPtrOutput)
}

func (o ProviderBasicAuthPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderBasicAuth) *string {
		if v == nil {
			return nil
		}
		return &v.Username
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ProviderAzureAuthOutput{})
	pulumi.RegisterOutputType(ProviderAzureAuthPtrOutput{})
	pulumi.RegisterOutputType(ProviderBasicAuthOutput{})
	pulumi.RegisterOutputType(ProviderBasicAuthPtrOutput{})
}
