// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type SecretScope struct {
	pulumi.CustomResourceState

	BackendType            pulumi.StringOutput    `pulumi:"backendType"`
	InitialManagePrincipal pulumi.StringPtrOutput `pulumi:"initialManagePrincipal"`
	Name                   pulumi.StringOutput    `pulumi:"name"`
}

// NewSecretScope registers a new resource with the given unique name, arguments, and options.
func NewSecretScope(ctx *pulumi.Context,
	name string, args *SecretScopeArgs, opts ...pulumi.ResourceOption) (*SecretScope, error) {
	if args == nil {
		args = &SecretScopeArgs{}
	}
	var resource SecretScope
	err := ctx.RegisterResource("databricks:index/secretScope:SecretScope", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecretScope gets an existing SecretScope resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecretScope(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecretScopeState, opts ...pulumi.ResourceOption) (*SecretScope, error) {
	var resource SecretScope
	err := ctx.ReadResource("databricks:index/secretScope:SecretScope", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecretScope resources.
type secretScopeState struct {
	BackendType            *string `pulumi:"backendType"`
	InitialManagePrincipal *string `pulumi:"initialManagePrincipal"`
	Name                   *string `pulumi:"name"`
}

type SecretScopeState struct {
	BackendType            pulumi.StringPtrInput
	InitialManagePrincipal pulumi.StringPtrInput
	Name                   pulumi.StringPtrInput
}

func (SecretScopeState) ElementType() reflect.Type {
	return reflect.TypeOf((*secretScopeState)(nil)).Elem()
}

type secretScopeArgs struct {
	InitialManagePrincipal *string `pulumi:"initialManagePrincipal"`
	Name                   *string `pulumi:"name"`
}

// The set of arguments for constructing a SecretScope resource.
type SecretScopeArgs struct {
	InitialManagePrincipal pulumi.StringPtrInput
	Name                   pulumi.StringPtrInput
}

func (SecretScopeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*secretScopeArgs)(nil)).Elem()
}
