// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class DatabricksNotebook
    {
        public static Task<DatabricksNotebookResult> InvokeAsync(DatabricksNotebookArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<DatabricksNotebookResult>("databricks:index/databricksNotebook:DatabricksNotebook", args ?? new DatabricksNotebookArgs(), options.WithVersion());
    }


    public sealed class DatabricksNotebookArgs : Pulumi.InvokeArgs
    {
        [Input("format", required: true)]
        public string Format { get; set; } = null!;

        [Input("path", required: true)]
        public string Path { get; set; } = null!;

        public DatabricksNotebookArgs()
        {
        }
    }


    [OutputType]
    public sealed class DatabricksNotebookResult
    {
        public readonly string Content;
        public readonly string Format;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Language;
        public readonly int ObjectId;
        public readonly string ObjectType;
        public readonly string Path;

        [OutputConstructor]
        private DatabricksNotebookResult(
            string content,

            string format,

            string id,

            string language,

            int objectId,

            string objectType,

            string path)
        {
            Content = content;
            Format = format;
            Id = id;
            Language = language;
            ObjectId = objectId;
            ObjectType = objectType;
            Path = path;
        }
    }
}
