// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public partial class DbfsFile : Pulumi.CustomResource
    {
        [Output("content")]
        public Output<string> Content { get; private set; } = null!;

        [Output("fileSize")]
        public Output<int> FileSize { get; private set; } = null!;

        [Output("mkdirs")]
        public Output<bool?> Mkdirs { get; private set; } = null!;

        [Output("overwrite")]
        public Output<bool?> Overwrite { get; private set; } = null!;

        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        [Output("validateRemoteFile")]
        public Output<bool?> ValidateRemoteFile { get; private set; } = null!;


        /// <summary>
        /// Create a DbfsFile resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DbfsFile(string name, DbfsFileArgs args, CustomResourceOptions? options = null)
            : base("databricks:index/dbfsFile:DbfsFile", name, args ?? new DbfsFileArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DbfsFile(string name, Input<string> id, DbfsFileState? state = null, CustomResourceOptions? options = null)
            : base("databricks:index/dbfsFile:DbfsFile", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DbfsFile resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DbfsFile Get(string name, Input<string> id, DbfsFileState? state = null, CustomResourceOptions? options = null)
        {
            return new DbfsFile(name, id, state, options);
        }
    }

    public sealed class DbfsFileArgs : Pulumi.ResourceArgs
    {
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        [Input("mkdirs")]
        public Input<bool>? Mkdirs { get; set; }

        [Input("overwrite")]
        public Input<bool>? Overwrite { get; set; }

        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        [Input("validateRemoteFile")]
        public Input<bool>? ValidateRemoteFile { get; set; }

        public DbfsFileArgs()
        {
        }
    }

    public sealed class DbfsFileState : Pulumi.ResourceArgs
    {
        [Input("content")]
        public Input<string>? Content { get; set; }

        [Input("fileSize")]
        public Input<int>? FileSize { get; set; }

        [Input("mkdirs")]
        public Input<bool>? Mkdirs { get; set; }

        [Input("overwrite")]
        public Input<bool>? Overwrite { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("validateRemoteFile")]
        public Input<bool>? ValidateRemoteFile { get; set; }

        public DbfsFileState()
        {
        }
    }
}
