// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetDefaultUserRoles
    {
        public static Task<GetDefaultUserRolesResult> InvokeAsync(GetDefaultUserRolesArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDefaultUserRolesResult>("databricks:index/getDefaultUserRoles:getDefaultUserRoles", args ?? new GetDefaultUserRolesArgs(), options.WithVersion());
    }


    public sealed class GetDefaultUserRolesArgs : Pulumi.InvokeArgs
    {
        [Input("defaultUsername", required: true)]
        public string DefaultUsername { get; set; } = null!;

        public GetDefaultUserRolesArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDefaultUserRolesResult
    {
        public readonly string DefaultUsername;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Roles;

        [OutputConstructor]
        private GetDefaultUserRolesResult(
            string defaultUsername,

            string id,

            ImmutableArray<string> roles)
        {
            DefaultUsername = defaultUsername;
            Id = id;
            Roles = roles;
        }
    }
}
