// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetDbfsFile
    {
        public static Task<GetDbfsFileResult> InvokeAsync(GetDbfsFileArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDbfsFileResult>("databricks:index/getDbfsFile:getDbfsFile", args ?? new GetDbfsFileArgs(), options.WithVersion());
    }


    public sealed class GetDbfsFileArgs : Pulumi.InvokeArgs
    {
        [Input("limitFileSize", required: true)]
        public bool LimitFileSize { get; set; }

        [Input("path", required: true)]
        public string Path { get; set; } = null!;

        public GetDbfsFileArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDbfsFileResult
    {
        public readonly string Content;
        public readonly int FileSize;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool LimitFileSize;
        public readonly string Path;

        [OutputConstructor]
        private GetDbfsFileResult(
            string content,

            int fileSize,

            string id,

            bool limitFileSize,

            string path)
        {
            Content = content;
            FileSize = fileSize;
            Id = id;
            LimitFileSize = limitFileSize;
            Path = path;
        }
    }
}
