// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetNotebookPaths
    {
        public static Task<GetNotebookPathsResult> InvokeAsync(GetNotebookPathsArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNotebookPathsResult>("databricks:index/getNotebookPaths:getNotebookPaths", args ?? new GetNotebookPathsArgs(), options.WithVersion());
    }


    public sealed class GetNotebookPathsArgs : Pulumi.InvokeArgs
    {
        [Input("path", required: true)]
        public string Path { get; set; } = null!;

        [Input("recursive", required: true)]
        public bool Recursive { get; set; }

        public GetNotebookPathsArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNotebookPathsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetNotebookPathsNotebookPathListResult> NotebookPathLists;
        public readonly string Path;
        public readonly bool Recursive;

        [OutputConstructor]
        private GetNotebookPathsResult(
            string id,

            ImmutableArray<Outputs.GetNotebookPathsNotebookPathListResult> notebookPathLists,

            string path,

            bool recursive)
        {
            Id = id;
            NotebookPathLists = notebookPathLists;
            Path = path;
            Recursive = recursive;
        }
    }
}
