// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetZones
    {
        public static Task<GetZonesResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetZonesResult>("databricks:index/getZones:getZones", InvokeArgs.Empty, options.WithVersion());
    }


    [OutputType]
    public sealed class GetZonesResult
    {
        public readonly string DefaultZone;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Zones;

        [OutputConstructor]
        private GetZonesResult(
            string defaultZone,

            string id,

            ImmutableArray<string> zones)
        {
            DefaultZone = defaultZone;
            Id = id;
            Zones = zones;
        }
    }
}
