// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Databricks
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("databricks");
        public static Pulumi.Databricks.Config.Types.AzureAuth? AzureAuth { get; set; } = __config.GetObject<Pulumi.Databricks.Config.Types.AzureAuth>("azureAuth");

        public static Pulumi.Databricks.Config.Types.BasicAuth? BasicAuth { get; set; } = __config.GetObject<Pulumi.Databricks.Config.Types.BasicAuth>("basicAuth");

        /// <summary>
        /// Location of the Databricks CLI credentials file, that is created by `databricks configure --token` command. By default,
        /// it is located in ~/.databrickscfg. Check https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication for
        /// docs. Config file credetials will only be used when host/token are not provided.
        /// </summary>
        public static string? ConfigFile { get; set; } = __config.Get("configFile");

        public static string? Host { get; set; } = __config.Get("host") ?? Utilities.GetEnv("DATABRICKS_HOST");

        /// <summary>
        /// Connection profile specified within ~/.databrickscfg. Please check
        /// https://docs.databricks.com/dev-tools/cli/index.html#connection-profiles for documentation.
        /// </summary>
        public static string? Profile { get; set; } = __config.Get("profile");

        public static string? Token { get; set; } = __config.Get("token") ?? Utilities.GetEnv("DATABRICKS_TOKEN");

        public static class Types
        {

             public class AzureAuth
             {
                public string AzureRegion { get; set; }
                public string ClientId { get; set; }
                public string ClientSecret { get; set; }
                public string ManagedResourceGroup { get; set; }
                public string ResourceGroup { get; set; }
                public string SubscriptionId { get; set; }
                public string TenantId { get; set; }
                public string WorkspaceName { get; set; }
            }

             public class BasicAuth
             {
                public string Password { get; set; }
                public string Username { get; set; }
            }
        }
    }
}
