// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Aws.Outputs
{

    [OutputType]
    public sealed class MwsWorkspacesNetworkErrorMessage
    {
        public readonly string? ErrorMessage;
        public readonly string? ErrorType;

        [OutputConstructor]
        private MwsWorkspacesNetworkErrorMessage(
            string? errorMessage,

            string? errorType)
        {
            ErrorMessage = errorMessage;
            ErrorType = errorType;
        }
    }
}
