# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables

class AzureAdlsGen1Mount(pulumi.CustomResource):
    client_id: pulumi.Output[str]
    client_secret_key: pulumi.Output[str]
    client_secret_scope: pulumi.Output[str]
    cluster_id: pulumi.Output[str]
    directory: pulumi.Output[str]
    mount_name: pulumi.Output[str]
    spark_conf_prefix: pulumi.Output[str]
    storage_resource_name: pulumi.Output[str]
    tenant_id: pulumi.Output[str]
    def __init__(__self__, resource_name, opts=None, client_id=None, client_secret_key=None, client_secret_scope=None, cluster_id=None, directory=None, mount_name=None, spark_conf_prefix=None, storage_resource_name=None, tenant_id=None, __props__=None, __name__=None, __opts__=None):
        """
        Create a AzureAdlsGen1Mount resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            if client_id is None:
                raise TypeError("Missing required property 'client_id'")
            __props__['client_id'] = client_id
            if client_secret_key is None:
                raise TypeError("Missing required property 'client_secret_key'")
            __props__['client_secret_key'] = client_secret_key
            if client_secret_scope is None:
                raise TypeError("Missing required property 'client_secret_scope'")
            __props__['client_secret_scope'] = client_secret_scope
            if cluster_id is None:
                raise TypeError("Missing required property 'cluster_id'")
            __props__['cluster_id'] = cluster_id
            __props__['directory'] = directory
            if mount_name is None:
                raise TypeError("Missing required property 'mount_name'")
            __props__['mount_name'] = mount_name
            __props__['spark_conf_prefix'] = spark_conf_prefix
            if storage_resource_name is None:
                raise TypeError("Missing required property 'storage_resource_name'")
            __props__['storage_resource_name'] = storage_resource_name
            if tenant_id is None:
                raise TypeError("Missing required property 'tenant_id'")
            __props__['tenant_id'] = tenant_id
        super(AzureAdlsGen1Mount, __self__).__init__(
            'databricks:index/azureAdlsGen1Mount:AzureAdlsGen1Mount',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, client_id=None, client_secret_key=None, client_secret_scope=None, cluster_id=None, directory=None, mount_name=None, spark_conf_prefix=None, storage_resource_name=None, tenant_id=None):
        """
        Get an existing AzureAdlsGen1Mount resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()

        __props__["client_id"] = client_id
        __props__["client_secret_key"] = client_secret_key
        __props__["client_secret_scope"] = client_secret_scope
        __props__["cluster_id"] = cluster_id
        __props__["directory"] = directory
        __props__["mount_name"] = mount_name
        __props__["spark_conf_prefix"] = spark_conf_prefix
        __props__["storage_resource_name"] = storage_resource_name
        __props__["tenant_id"] = tenant_id
        return AzureAdlsGen1Mount(resource_name, opts=opts, __props__=__props__)
    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

