# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables

class GetDefaultUserRolesResult:
    """
    A collection of values returned by getDefaultUserRoles.
    """
    def __init__(__self__, default_username=None, id=None, roles=None):
        if default_username and not isinstance(default_username, str):
            raise TypeError("Expected argument 'default_username' to be a str")
        __self__.default_username = default_username
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        __self__.id = id
        """
        The provider-assigned unique ID for this managed resource.
        """
        if roles and not isinstance(roles, list):
            raise TypeError("Expected argument 'roles' to be a list")
        __self__.roles = roles
class AwaitableGetDefaultUserRolesResult(GetDefaultUserRolesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDefaultUserRolesResult(
            default_username=self.default_username,
            id=self.id,
            roles=self.roles)

def get_default_user_roles(default_username=None,opts=None):
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()


    __args__['defaultUsername'] = default_username
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = utilities.get_version()
    __ret__ = pulumi.runtime.invoke('databricks:index/getDefaultUserRoles:getDefaultUserRoles', __args__, opts=opts).value

    return AwaitableGetDefaultUserRolesResult(
        default_username=__ret__.get('defaultUsername'),
        id=__ret__.get('id'),
        roles=__ret__.get('roles'))
