// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class ClusterLibraryMaven
    {
        public readonly string? Coordinates;
        public readonly ImmutableArray<string> Exclusions;
        public readonly ImmutableArray<string> Messages;
        public readonly string? Repo;
        public readonly string? Status;

        [OutputConstructor]
        private ClusterLibraryMaven(
            string? coordinates,

            ImmutableArray<string> exclusions,

            ImmutableArray<string> messages,

            string? repo,

            string? status)
        {
            Coordinates = coordinates;
            Exclusions = exclusions;
            Messages = messages;
            Repo = repo;
            Status = status;
        }
    }
}
