// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class JobNewCluster
    {
        public readonly Outputs.JobNewClusterAutoscale? Autoscale;
        public readonly int? AutoterminationMinutes;
        public readonly Outputs.JobNewClusterAwsAttributes? AwsAttributes;
        public readonly Outputs.JobNewClusterClusterLogConf? ClusterLogConf;
        public readonly string? ClusterName;
        public readonly ImmutableDictionary<string, object>? CustomTags;
        public readonly Outputs.JobNewClusterDockerImage? DockerImage;
        public readonly string? DriverNodeTypeId;
        public readonly bool? EnableElasticDisk;
        public readonly ImmutableArray<Outputs.JobNewClusterInitScript> InitScripts;
        public readonly string? InstancePoolId;
        public readonly string? NodeTypeId;
        public readonly int? NumWorkers;
        public readonly ImmutableDictionary<string, object>? SparkConf;
        public readonly ImmutableDictionary<string, object>? SparkEnvVars;
        public readonly string? SparkVersion;
        public readonly ImmutableArray<string> SshPublicKeys;

        [OutputConstructor]
        private JobNewCluster(
            Outputs.JobNewClusterAutoscale? autoscale,

            int? autoterminationMinutes,

            Outputs.JobNewClusterAwsAttributes? awsAttributes,

            Outputs.JobNewClusterClusterLogConf? clusterLogConf,

            string? clusterName,

            ImmutableDictionary<string, object>? customTags,

            Outputs.JobNewClusterDockerImage? dockerImage,

            string? driverNodeTypeId,

            bool? enableElasticDisk,

            ImmutableArray<Outputs.JobNewClusterInitScript> initScripts,

            string? instancePoolId,

            string? nodeTypeId,

            int? numWorkers,

            ImmutableDictionary<string, object>? sparkConf,

            ImmutableDictionary<string, object>? sparkEnvVars,

            string? sparkVersion,

            ImmutableArray<string> sshPublicKeys)
        {
            Autoscale = autoscale;
            AutoterminationMinutes = autoterminationMinutes;
            AwsAttributes = awsAttributes;
            ClusterLogConf = clusterLogConf;
            ClusterName = clusterName;
            CustomTags = customTags;
            DockerImage = dockerImage;
            DriverNodeTypeId = driverNodeTypeId;
            EnableElasticDisk = enableElasticDisk;
            InitScripts = initScripts;
            InstancePoolId = instancePoolId;
            NodeTypeId = nodeTypeId;
            NumWorkers = numWorkers;
            SparkConf = sparkConf;
            SparkEnvVars = sparkEnvVars;
            SparkVersion = sparkVersion;
            SshPublicKeys = sshPublicKeys;
        }
    }
}
