// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Outputs
{

    [OutputType]
    public sealed class ProviderAzureAuth
    {
        public readonly string AzureRegion;
        public readonly string ClientId;
        public readonly string ClientSecret;
        public readonly string ManagedResourceGroup;
        public readonly string ResourceGroup;
        public readonly string SubscriptionId;
        public readonly string TenantId;
        public readonly string WorkspaceName;

        [OutputConstructor]
        private ProviderAzureAuth(
            string azureRegion,

            string clientId,

            string clientSecret,

            string managedResourceGroup,

            string resourceGroup,

            string subscriptionId,

            string tenantId,

            string workspaceName)
        {
            AzureRegion = azureRegion;
            ClientId = clientId;
            ClientSecret = clientSecret;
            ManagedResourceGroup = managedResourceGroup;
            ResourceGroup = resourceGroup;
            SubscriptionId = subscriptionId;
            TenantId = tenantId;
            WorkspaceName = workspaceName;
        }
    }
}
