// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package azure

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type AzureAdlsGen1Mount struct {
	pulumi.CustomResourceState

	ClientId            pulumi.StringOutput    `pulumi:"clientId"`
	ClientSecretKey     pulumi.StringOutput    `pulumi:"clientSecretKey"`
	ClientSecretScope   pulumi.StringOutput    `pulumi:"clientSecretScope"`
	ClusterId           pulumi.StringOutput    `pulumi:"clusterId"`
	Directory           pulumi.StringOutput    `pulumi:"directory"`
	MountName           pulumi.StringOutput    `pulumi:"mountName"`
	SparkConfPrefix     pulumi.StringPtrOutput `pulumi:"sparkConfPrefix"`
	StorageResourceName pulumi.StringOutput    `pulumi:"storageResourceName"`
	TenantId            pulumi.StringOutput    `pulumi:"tenantId"`
}

// NewAzureAdlsGen1Mount registers a new resource with the given unique name, arguments, and options.
func NewAzureAdlsGen1Mount(ctx *pulumi.Context,
	name string, args *AzureAdlsGen1MountArgs, opts ...pulumi.ResourceOption) (*AzureAdlsGen1Mount, error) {
	if args == nil || args.ClientId == nil {
		return nil, errors.New("missing required argument 'ClientId'")
	}
	if args == nil || args.ClientSecretKey == nil {
		return nil, errors.New("missing required argument 'ClientSecretKey'")
	}
	if args == nil || args.ClientSecretScope == nil {
		return nil, errors.New("missing required argument 'ClientSecretScope'")
	}
	if args == nil || args.ClusterId == nil {
		return nil, errors.New("missing required argument 'ClusterId'")
	}
	if args == nil || args.MountName == nil {
		return nil, errors.New("missing required argument 'MountName'")
	}
	if args == nil || args.StorageResourceName == nil {
		return nil, errors.New("missing required argument 'StorageResourceName'")
	}
	if args == nil || args.TenantId == nil {
		return nil, errors.New("missing required argument 'TenantId'")
	}
	if args == nil {
		args = &AzureAdlsGen1MountArgs{}
	}
	var resource AzureAdlsGen1Mount
	err := ctx.RegisterResource("databricks:azure/azureAdlsGen1Mount:AzureAdlsGen1Mount", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureAdlsGen1Mount gets an existing AzureAdlsGen1Mount resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureAdlsGen1Mount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureAdlsGen1MountState, opts ...pulumi.ResourceOption) (*AzureAdlsGen1Mount, error) {
	var resource AzureAdlsGen1Mount
	err := ctx.ReadResource("databricks:azure/azureAdlsGen1Mount:AzureAdlsGen1Mount", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureAdlsGen1Mount resources.
type azureAdlsGen1MountState struct {
	ClientId            *string `pulumi:"clientId"`
	ClientSecretKey     *string `pulumi:"clientSecretKey"`
	ClientSecretScope   *string `pulumi:"clientSecretScope"`
	ClusterId           *string `pulumi:"clusterId"`
	Directory           *string `pulumi:"directory"`
	MountName           *string `pulumi:"mountName"`
	SparkConfPrefix     *string `pulumi:"sparkConfPrefix"`
	StorageResourceName *string `pulumi:"storageResourceName"`
	TenantId            *string `pulumi:"tenantId"`
}

type AzureAdlsGen1MountState struct {
	ClientId            pulumi.StringPtrInput
	ClientSecretKey     pulumi.StringPtrInput
	ClientSecretScope   pulumi.StringPtrInput
	ClusterId           pulumi.StringPtrInput
	Directory           pulumi.StringPtrInput
	MountName           pulumi.StringPtrInput
	SparkConfPrefix     pulumi.StringPtrInput
	StorageResourceName pulumi.StringPtrInput
	TenantId            pulumi.StringPtrInput
}

func (AzureAdlsGen1MountState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureAdlsGen1MountState)(nil)).Elem()
}

type azureAdlsGen1MountArgs struct {
	ClientId            string  `pulumi:"clientId"`
	ClientSecretKey     string  `pulumi:"clientSecretKey"`
	ClientSecretScope   string  `pulumi:"clientSecretScope"`
	ClusterId           string  `pulumi:"clusterId"`
	Directory           *string `pulumi:"directory"`
	MountName           string  `pulumi:"mountName"`
	SparkConfPrefix     *string `pulumi:"sparkConfPrefix"`
	StorageResourceName string  `pulumi:"storageResourceName"`
	TenantId            string  `pulumi:"tenantId"`
}

// The set of arguments for constructing a AzureAdlsGen1Mount resource.
type AzureAdlsGen1MountArgs struct {
	ClientId            pulumi.StringInput
	ClientSecretKey     pulumi.StringInput
	ClientSecretScope   pulumi.StringInput
	ClusterId           pulumi.StringInput
	Directory           pulumi.StringPtrInput
	MountName           pulumi.StringInput
	SparkConfPrefix     pulumi.StringPtrInput
	StorageResourceName pulumi.StringInput
	TenantId            pulumi.StringInput
}

func (AzureAdlsGen1MountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureAdlsGen1MountArgs)(nil)).Elem()
}
