// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";

export interface ProviderAzureAuth {
    azureRegion: pulumi.Input<string>;
    clientId: pulumi.Input<string>;
    clientSecret: pulumi.Input<string>;
    managedResourceGroup: pulumi.Input<string>;
    resourceGroup: pulumi.Input<string>;
    subscriptionId: pulumi.Input<string>;
    tenantId: pulumi.Input<string>;
    workspaceName: pulumi.Input<string>;
}

export interface ProviderBasicAuth {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
