// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Aws
{
    public partial class MwsStorageConfigurations : Pulumi.CustomResource
    {
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        [Output("bucketName")]
        public Output<string> BucketName { get; private set; } = null!;

        [Output("creationTime")]
        public Output<int> CreationTime { get; private set; } = null!;

        [Output("storageConfigurationId")]
        public Output<string> StorageConfigurationId { get; private set; } = null!;

        [Output("storageConfigurationName")]
        public Output<string> StorageConfigurationName { get; private set; } = null!;


        /// <summary>
        /// Create a MwsStorageConfigurations resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MwsStorageConfigurations(string name, MwsStorageConfigurationsArgs args, CustomResourceOptions? options = null)
            : base("databricks:aws/mwsStorageConfigurations:MwsStorageConfigurations", name, args ?? new MwsStorageConfigurationsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MwsStorageConfigurations(string name, Input<string> id, MwsStorageConfigurationsState? state = null, CustomResourceOptions? options = null)
            : base("databricks:aws/mwsStorageConfigurations:MwsStorageConfigurations", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MwsStorageConfigurations resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MwsStorageConfigurations Get(string name, Input<string> id, MwsStorageConfigurationsState? state = null, CustomResourceOptions? options = null)
        {
            return new MwsStorageConfigurations(name, id, state, options);
        }
    }

    public sealed class MwsStorageConfigurationsArgs : Pulumi.ResourceArgs
    {
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        [Input("bucketName", required: true)]
        public Input<string> BucketName { get; set; } = null!;

        [Input("storageConfigurationName", required: true)]
        public Input<string> StorageConfigurationName { get; set; } = null!;

        public MwsStorageConfigurationsArgs()
        {
        }
    }

    public sealed class MwsStorageConfigurationsState : Pulumi.ResourceArgs
    {
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("bucketName")]
        public Input<string>? BucketName { get; set; }

        [Input("creationTime")]
        public Input<int>? CreationTime { get; set; }

        [Input("storageConfigurationId")]
        public Input<string>? StorageConfigurationId { get; set; }

        [Input("storageConfigurationName")]
        public Input<string>? StorageConfigurationName { get; set; }

        public MwsStorageConfigurationsState()
        {
        }
    }
}
