// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Inputs
{

    public sealed class ClusterLibraryWhlGetArgs : Pulumi.ResourceArgs
    {
        [Input("messages")]
        private InputList<string>? _messages;
        public InputList<string> Messages
        {
            get => _messages ?? (_messages = new InputList<string>());
            set => _messages = value;
        }

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        public ClusterLibraryWhlGetArgs()
        {
        }
    }
}
