// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Inputs
{

    public sealed class ClusterLibraryCranGetArgs : Pulumi.ResourceArgs
    {
        [Input("messages")]
        public Input<string>? Messages { get; set; }

        [Input("package")]
        public Input<string>? Package { get; set; }

        [Input("repo")]
        public Input<string>? Repo { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        public ClusterLibraryCranGetArgs()
        {
        }
    }
}
