// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatabricksToken extends pulumi.CustomResource {
    /**
     * Get an existing DatabricksToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabricksTokenState, opts?: pulumi.CustomResourceOptions): DatabricksToken {
        return new DatabricksToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'databricks:index/databricksToken:DatabricksToken';

    /**
     * Returns true if the given object is an instance of DatabricksToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatabricksToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatabricksToken.__pulumiType;
    }

    public readonly comment!: pulumi.Output<string | undefined>;
    public readonly creationTime!: pulumi.Output<number>;
    public readonly expiryTime!: pulumi.Output<number>;
    public readonly lifetimeSeconds!: pulumi.Output<number | undefined>;
    public /*out*/ readonly tokenValue!: pulumi.Output<string>;

    /**
     * Create a DatabricksToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DatabricksTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabricksTokenArgs | DatabricksTokenState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as DatabricksTokenState | undefined;
            inputs["comment"] = state ? state.comment : undefined;
            inputs["creationTime"] = state ? state.creationTime : undefined;
            inputs["expiryTime"] = state ? state.expiryTime : undefined;
            inputs["lifetimeSeconds"] = state ? state.lifetimeSeconds : undefined;
            inputs["tokenValue"] = state ? state.tokenValue : undefined;
        } else {
            const args = argsOrState as DatabricksTokenArgs | undefined;
            inputs["comment"] = args ? args.comment : undefined;
            inputs["creationTime"] = args ? args.creationTime : undefined;
            inputs["expiryTime"] = args ? args.expiryTime : undefined;
            inputs["lifetimeSeconds"] = args ? args.lifetimeSeconds : undefined;
            inputs["tokenValue"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(DatabricksToken.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DatabricksToken resources.
 */
export interface DatabricksTokenState {
    readonly comment?: pulumi.Input<string>;
    readonly creationTime?: pulumi.Input<number>;
    readonly expiryTime?: pulumi.Input<number>;
    readonly lifetimeSeconds?: pulumi.Input<number>;
    readonly tokenValue?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DatabricksToken resource.
 */
export interface DatabricksTokenArgs {
    readonly comment?: pulumi.Input<string>;
    readonly creationTime?: pulumi.Input<number>;
    readonly expiryTime?: pulumi.Input<number>;
    readonly lifetimeSeconds?: pulumi.Input<number>;
}
