// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function DbfsFilePaths(args: DbfsFilePathsArgs, opts?: pulumi.InvokeOptions): Promise<DbfsFilePathsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("databricks:index/dbfsFilePaths:DbfsFilePaths", {
        "path": args.path,
        "recursive": args.recursive,
    }, opts);
}

/**
 * A collection of arguments for invoking DbfsFilePaths.
 */
export interface DbfsFilePathsArgs {
    readonly path: string;
    readonly recursive: boolean;
}

/**
 * A collection of values returned by DbfsFilePaths.
 */
export interface DbfsFilePathsResult {
    readonly path: string;
    readonly pathLists: outputs.DbfsFilePathsPathList[];
    readonly recursive: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
