// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDbfsFilePaths(args: GetDbfsFilePathsArgs, opts?: pulumi.InvokeOptions): Promise<GetDbfsFilePathsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("databricks:index/getDbfsFilePaths:getDbfsFilePaths", {
        "path": args.path,
        "recursive": args.recursive,
    }, opts);
}

/**
 * A collection of arguments for invoking getDbfsFilePaths.
 */
export interface GetDbfsFilePathsArgs {
    readonly path: string;
    readonly recursive: boolean;
}

/**
 * A collection of values returned by getDbfsFilePaths.
 */
export interface GetDbfsFilePathsResult {
    readonly path: string;
    readonly pathLists: outputs.GetDbfsFilePathsPathList[];
    readonly recursive: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
