// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDefaultUserRoles(args: GetDefaultUserRolesArgs, opts?: pulumi.InvokeOptions): Promise<GetDefaultUserRolesResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("databricks:index/getDefaultUserRoles:getDefaultUserRoles", {
        "defaultUsername": args.defaultUsername,
    }, opts);
}

/**
 * A collection of arguments for invoking getDefaultUserRoles.
 */
export interface GetDefaultUserRolesArgs {
    readonly defaultUsername: string;
}

/**
 * A collection of values returned by getDefaultUserRoles.
 */
export interface GetDefaultUserRolesResult {
    readonly defaultUsername: string;
    readonly roles: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
