// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDbfsFile(args: GetDbfsFileArgs, opts?: pulumi.InvokeOptions): Promise<GetDbfsFileResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("databricks:index/getDbfsFile:getDbfsFile", {
        "limitFileSize": args.limitFileSize,
        "path": args.path,
    }, opts);
}

/**
 * A collection of arguments for invoking getDbfsFile.
 */
export interface GetDbfsFileArgs {
    readonly limitFileSize: boolean;
    readonly path: string;
}

/**
 * A collection of values returned by getDbfsFile.
 */
export interface GetDbfsFileResult {
    readonly content: string;
    readonly fileSize: number;
    readonly limitFileSize: boolean;
    readonly path: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
