// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNotebook(args: GetNotebookArgs, opts?: pulumi.InvokeOptions): Promise<GetNotebookResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("databricks:index/getNotebook:getNotebook", {
        "format": args.format,
        "path": args.path,
    }, opts);
}

/**
 * A collection of arguments for invoking getNotebook.
 */
export interface GetNotebookArgs {
    readonly format: string;
    readonly path: string;
}

/**
 * A collection of values returned by getNotebook.
 */
export interface GetNotebookResult {
    readonly content: string;
    readonly format: string;
    readonly language: string;
    readonly objectId: number;
    readonly objectType: string;
    readonly path: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
