// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNotebookPaths(args: GetNotebookPathsArgs, opts?: pulumi.InvokeOptions): Promise<GetNotebookPathsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("databricks:index/getNotebookPaths:getNotebookPaths", {
        "path": args.path,
        "recursive": args.recursive,
    }, opts);
}

/**
 * A collection of arguments for invoking getNotebookPaths.
 */
export interface GetNotebookPathsArgs {
    readonly path: string;
    readonly recursive: boolean;
}

/**
 * A collection of values returned by getNotebookPaths.
 */
export interface GetNotebookPathsResult {
    readonly notebookPathLists: outputs.GetNotebookPathsNotebookPathList[];
    readonly path: string;
    readonly recursive: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
