// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class MwsCredentials extends pulumi.CustomResource {
    /**
     * Get an existing MwsCredentials resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MwsCredentialsState, opts?: pulumi.CustomResourceOptions): MwsCredentials {
        return new MwsCredentials(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'databricks:index/mwsCredentials:MwsCredentials';

    /**
     * Returns true if the given object is an instance of MwsCredentials.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MwsCredentials {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MwsCredentials.__pulumiType;
    }

    public readonly accountId!: pulumi.Output<string>;
    public /*out*/ readonly creationTime!: pulumi.Output<number>;
    public /*out*/ readonly credentialsId!: pulumi.Output<string>;
    public readonly credentialsName!: pulumi.Output<string>;
    public /*out*/ readonly externalId!: pulumi.Output<string>;
    public readonly roleArn!: pulumi.Output<string>;

    /**
     * Create a MwsCredentials resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MwsCredentialsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MwsCredentialsArgs | MwsCredentialsState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as MwsCredentialsState | undefined;
            inputs["accountId"] = state ? state.accountId : undefined;
            inputs["creationTime"] = state ? state.creationTime : undefined;
            inputs["credentialsId"] = state ? state.credentialsId : undefined;
            inputs["credentialsName"] = state ? state.credentialsName : undefined;
            inputs["externalId"] = state ? state.externalId : undefined;
            inputs["roleArn"] = state ? state.roleArn : undefined;
        } else {
            const args = argsOrState as MwsCredentialsArgs | undefined;
            if (!args || args.accountId === undefined) {
                throw new Error("Missing required property 'accountId'");
            }
            if (!args || args.credentialsName === undefined) {
                throw new Error("Missing required property 'credentialsName'");
            }
            if (!args || args.roleArn === undefined) {
                throw new Error("Missing required property 'roleArn'");
            }
            inputs["accountId"] = args ? args.accountId : undefined;
            inputs["credentialsName"] = args ? args.credentialsName : undefined;
            inputs["roleArn"] = args ? args.roleArn : undefined;
            inputs["creationTime"] = undefined /*out*/;
            inputs["credentialsId"] = undefined /*out*/;
            inputs["externalId"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(MwsCredentials.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MwsCredentials resources.
 */
export interface MwsCredentialsState {
    readonly accountId?: pulumi.Input<string>;
    readonly creationTime?: pulumi.Input<number>;
    readonly credentialsId?: pulumi.Input<string>;
    readonly credentialsName?: pulumi.Input<string>;
    readonly externalId?: pulumi.Input<string>;
    readonly roleArn?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a MwsCredentials resource.
 */
export interface MwsCredentialsArgs {
    readonly accountId: pulumi.Input<string>;
    readonly credentialsName: pulumi.Input<string>;
    readonly roleArn: pulumi.Input<string>;
}
