// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SecretAcl extends pulumi.CustomResource {
    /**
     * Get an existing SecretAcl resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretAclState, opts?: pulumi.CustomResourceOptions): SecretAcl {
        return new SecretAcl(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'databricks:index/secretAcl:SecretAcl';

    /**
     * Returns true if the given object is an instance of SecretAcl.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretAcl {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretAcl.__pulumiType;
    }

    public readonly permission!: pulumi.Output<string>;
    public readonly principal!: pulumi.Output<string>;
    public readonly scope!: pulumi.Output<string>;

    /**
     * Create a SecretAcl resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretAclArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretAclArgs | SecretAclState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SecretAclState | undefined;
            inputs["permission"] = state ? state.permission : undefined;
            inputs["principal"] = state ? state.principal : undefined;
            inputs["scope"] = state ? state.scope : undefined;
        } else {
            const args = argsOrState as SecretAclArgs | undefined;
            if (!args || args.permission === undefined) {
                throw new Error("Missing required property 'permission'");
            }
            if (!args || args.principal === undefined) {
                throw new Error("Missing required property 'principal'");
            }
            if (!args || args.scope === undefined) {
                throw new Error("Missing required property 'scope'");
            }
            inputs["permission"] = args ? args.permission : undefined;
            inputs["principal"] = args ? args.principal : undefined;
            inputs["scope"] = args ? args.scope : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(SecretAcl.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretAcl resources.
 */
export interface SecretAclState {
    readonly permission?: pulumi.Input<string>;
    readonly principal?: pulumi.Input<string>;
    readonly scope?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SecretAcl resource.
 */
export interface SecretAclArgs {
    readonly permission: pulumi.Input<string>;
    readonly principal: pulumi.Input<string>;
    readonly scope: pulumi.Input<string>;
}
